import {
  Astro,
  Css,
  Docker,
  Drizzle,
  Express,
  Github,
  Graphql,
  Html5,
  Javascript,
  Jest,
  Jquery,
  Json,
  Mysql,
  Netlify,
  Nextjs,
  Nodejs,
  Php,
  Postgresql,
  Postman,
  Python,
  React,
  Reactquery,
  Redux,
  Remix,
  Sap,
  Shadcn,
  Shopify,
  Supabase,
  Tailwindcss,
  Tanstack,
  Threejs,
  Typescript,
  Unity,
  Vercel,
  Xml,
  Yaml,
} from "@/components/icons/svg-icons";
import { Box } from "lucide-react";
import type { SVGProps } from "react";

type IconType = React.ComponentType<SVGProps<SVGSVGElement>>;
export const iconsMap: Record<string, IconType> = {
  react: React,
  tailwindcss: Tailwindcss,
  typescript: Typescript,
  css: Css,
  docker: Docker,
  drizzle: Drizzle,
  express: Express,
  html: Html5,
  graphql: Graphql,
  javascript: Javascript,
  jest: Jest,
  jquery: Jquery,
  json: Json,
  mysql: Mysql,
  netlify: Netlify,
  nextjs: Nextjs,
  nodejs: Nodejs,
  php: Php,
  postgresql: Postgresql,
  postman: Postman,
  redux: Redux,
  remix: Remix,
  sap: Sap,
  shadcn: Shadcn,
  github: Github,
  shopify: Shopify,
  supabase: Supabase,
  threejs: Threejs,
  unity: Unity,
  vercel: Vercel,
  xml: Xml,
  yaml: Yaml,
  python: Python,
  reactquery: Reactquery,
  astro: Astro,
  tanstack: Tanstack,
};
const fallbackIcon = Box;
export default function getIcon(iconName: string): IconType {
  const loweredIcon = iconName.toLowerCase();
  return iconsMap[loweredIcon] || fallbackIcon;
}
