import { TimelineEntryProps } from "@/interfaces";

export default [
  {
    title: "Q1 2025",
    content: {
      status: "done",
      title: "Motion Provider",
      output:
        "I discovered my intuitive ability to create and maintain React components with ease.",
      role: "Entrepreneur",
      githubLink: "https://github.com/Masculinn/motion-provider",
      link: "/motion-provider",
      usedTechs: ["React", "TailwindCSS", "TypeScript", "Motion", "Nextjs"],
      desc: "Accelerate your React component animations by up to 4x with seamless performance and precision, built entirely in React and TypeScript for a smooth, type-safe development experience.",
      images: [
        "/assets/projects/thumbs/saas-thumb.gif",
        "/assets/projects/thumbs/crypto-thumb.gif",
        "/assets/projects/thumbs/agency-thumb.gif",
        "/assets/projects/thumbs/nft-thumb.gif",
      ],
    },
  },
  {
    title: "Q1 2025",
    content: {
      status: "done",
      title: "burak.dev",
      role: "Entrepreneur",
      desc: "A blog project aimed at fostering connections among individuals passionate about self-improvement in software technologies. The platform emphasizes community engagement, sharing useful creations, and exploring innovative ideas related to technology.",
      images: [],
      link: "https://burak.dev",
      githubLink: undefined,
      usedTechs: [
        "React",
        "Redux",
        "Next.js",
        "TailwindCSS",
        "TypeScript",
        "Motion",
        "Shadcn",
        "Supabase",
      ],
      output: "You already seeing the magic!",
    },
  },
  {
    title: "Q4 2024",
    content: {
      status: "paused",
      title: "teezy.com",
      role: "Entrepreneur",
      desc: "A self-initiated social music platform where users can listen to music, create profiles, upload and share tracks, explore other profiles, and enjoy AI-modified versions of tracks. It aimed to be a more interactive and community-driven version of Spotify.",
      images: [
        "/assets/timeline/teezy/1.webp",
        "/assets/timeline/teezy/2.webp",
        "/assets/timeline/teezy/3.webp",
        "/assets/timeline/teezy/4.webp",
      ],
      link: undefined,
      githubLink: undefined,
      usedTechs: [
        "React",
        "Redux",
        "TailwindCSS",
        "TypeScript",
        "Supabase",
        "Next.js",
        "nextui",
        "PostgreSQL",
      ],
      output:
        "Learned the importance of iterative development: start small (bicycle) and gradually evolve the product (motorcycle, car) which means MVP. I am saying again not starting from building a car.",
    },
  },
  {
    title: "Q3 2024",
    content: {
      status: "done",
      title: "ERP Cloudy",
      role: "Software Development Team Lead",
      desc: "Promoted as a team lead for a high-stakes project integrating a government invoice system (Krajowy System e-Faktur - KSEF) into existing architecture. Collaborated with accountants, digitized processes, and managed team development.",
      images: [
        "/assets/timeline/erp-cloudy/1.webp",
        "/assets/timeline/erp-cloudy/2.webp",
      ],
      link: "https://merkur.erpcloudy.com/",
      githubLink: undefined,
      usedTechs: [
        "Core JavaScript",
        "XML",
        "SOAP",
        "SAP",
        "Microsoft .NET XAF",
      ],
      output:
        "I understood that how one government may lead to apocalypse by doing EXTREMELY MAJOR changes in their system...",
    },
  },
  {
    title: "Q3 2024",
    content: {
      status: "done",
      title: "Dashboard App",
      role: "Lead Information Technology Specialist",
      desc: "Developed a student tracking application for a consultancy firm, allowing Turkish students studying in Poland to track visa statuses, accommodations, appointments, and documents, with secure real-time chat.",
      images: [
        "/assets/timeline/olympos-dashboard/1.webp",
        "/assets/timeline/olympos-dashboard/2.webp",
        "/assets/timeline/olympos-dashboard/3.webp",
        "/assets/timeline/olympos-dashboard/4.webp",
      ],
      link: "https://olymposedu.com/login/",
      githubLink: "https://github.com/Masculinn/education-crm",
      usedTechs: [
        "Next.js",
        "Remix",
        "React",
        "Redux",
        "Supabase",
        "Bcrypt",
        "react-spring",
        "TailwindCSS",
      ],
      output:
        "Enhanced client-side data manipulation skills and WebSocket security.",
    },
  },
  {
    title: "Q2 2024",
    content: {
      status: "done",
      title: "atlanticmedi.com",
      role: "Lead Information Technology Specialist",
      desc: "Built a static web app for the medical tourism sector with over 165 pages in Polish and English. Included an independent chatbot and provided comprehensive information on medical treatments and services.",
      images: [
        "/assets/timeline/atlanticmedi/1.webp",
        "/assets/timeline/atlanticmedi/2.webp",
        "/assets/timeline/atlanticmedi/3.webp",
        "/assets/timeline/atlanticmedi/4.webp",
      ],
      link: "https://atlanticmedi.com/",
      githubLink: undefined,
      usedTechs: [
        "Next.js",
        "React",
        "Redux",
        "react-spring",
        "Three.js",
        "TailwindCSS",
      ],
      output:
        "I would just say data scrapping with bypassing recaptcha and SSG for this one.",
    },
  },
  {
    title: "Q1 2024",
    content: {
      status: "done",
      title: "olymposedu.com",
      role: "Lead Information Technology Specialist",
      desc: "Developed a web app for students aspiring to study in Poland, including information on universities, pricing, articles, and more.",
      images: [
        "/assets/timeline/olymposedu/1.webp",
        "/assets/timeline/olymposedu/2.webp",
        "/assets/timeline/olymposedu/3.webp",
        "/assets/timeline/olymposedu/4.webp",
      ],
      link: "https://olymposedu.com/",
      githubLink: "https://github.com/Masculinn/olymposedu",
      usedTechs: [
        "Next.js",
        "Remix",
        "React",
        "Redux",
        "Supabase",
        "Bcrypt",
        "react-spring",
      ],
      output: "Sharpened advanced SEO techniques using JSON-LD and GraphQL.",
    },
  },
  {
    title: "Q4 2023",
    content: {
      status: "done",
      title: "finfluencer.com",
      role: "Lead Information Technology Specialist",
      desc: "Developed a SPA integrated into the company's website for business analytics for Turkish financial influencers.",
      images: [
        "/assets/timeline/finfluencer/1.webp",
        "/assets/timeline/finfluencer/2.webp",
        "/assets/timeline/finfluencer/3.webp",
        "/assets/timeline/finfluencer/4.webp",
      ],
      link: "https://atlanticvalleypartners.com/tr/finfluencer-ajansimiz.html",
      githubLink: "https://github.com/Masculinn/olymposedu",
      usedTechs: ["Next.js", "React", "Redux", "react-spring"],
      output:
        "Gained hands-on experience with data visualization libraries like Chart.js.",
    },
  },
  {
    title: "Q4 2023",
    content: {
      status: "done",
      title: "santaesmeraldas.com",
      role: "IT Specialist",
      desc: "Developed a jewelry e-commerce website from scratch, listing over 150 products. Focused on improving UX and implementing marketing strategies.",
      images: [
        "/assets/timeline/santa-esmeralda/1.webp",
        "/assets/timeline/santa-esmeralda/2.webp",
        "/assets/timeline/santa-esmeralda/3.webp",
        "/assets/timeline/santa-esmeralda/4.webp",
      ],
      link: "https://santaesmeraldas.com/",
      githubLink: undefined,
      usedTechs: ["Shopify", "Liquid", "Core JavaScript", "CSS", "HTML"],
      output:
        "Learned the importance of marketing strategies in competitive e-commerce sectors and how they often outweigh technical website capabilities.",
    },
  },
  {
    title: "Q3 2023",
    content: {
      images: [
        "/assets/timeline/erp-cloudy/1.webp",
        "/assets/timeline/erp-cloudy/2.webp",
      ],
      output:
        "Learned to approach problems from a broader perspective and break them down into manageable parts.",
      role: "Software developer/integrator",
      status: "done",
      title: "ERP Cloudy",
      usedTechs: [
        "Core JavaScript",
        "XML",
        "SOAP",
        "SAP",
        "Microsoft .NET XAF",
      ],
      desc: "Joined the largest e-transformation software firm based on Turkey, serving over 370,000 clients.While Working from Poland for this firm, simultaneously worked at a consulting firm. Focused on understanding and implementing solutions for the Polish government’s e-invoice system (Krajowy System e-Faktur - KSEF). Worked primarily as an integrator developer, developing system-based solutions and supporting the team.",
      githubLink: undefined,
      link: "https://merkur.erpcloudy.com/",
    },
  },
  {
    title: "Q2 2023",
    content: {
      images: [
        "/assets/timeline/atlantic/1.webp",
        "/assets/timeline/atlantic/2.webp",
        "/assets/timeline/atlantic/3.webp",
        "/assets/timeline/atlantic/4.webp",
      ],
      output: "",
      role: "Software Developer",
      status: "done",
      title: "atlanticvalleypartners.com",
      usedTechs: ["Next.js", "React", "Redux", "react-spring", "TailwindCSS"],
      desc: "Cupidatat reprehenderit enim nisi cillum. Deserunt commodo enim minim deserunt sunt duis. Ipsum fugiat fugiat adipisicing aliqua ad cupidatat nisi cillum sit in eiusmod enim nostrud.",
      githubLink: "https://github.com/Masculinn/atlanticvalleypartners",
      link: "https://atlanticvalleypartners.com",
    },
  },
  {
    title: "2022",
    content: {
      status: "done",
      title: "The Last Human",
      role: "Intern Game Developer",
      desc: "Worked on a mobile non-stop survival game using the Unity game engine, focusing on shaders, graphics optimization, and AI.",
      images: [],
      link: undefined,
      githubLink: undefined,
      usedTechs: ["C#", "Unity", "PlasticCSM", "Mixamo"],
      output: "Gained hands-on experience in game development.",
    },
  },
  {
    title: "2021",
    content: {
      status: "done",
      title: "Freelancer",
      role: "Web developer",
      desc: "Worked on various freelancing platforms like Fiverr and Upwork, creating web applications based on client requirements. Gained experience in understanding client needs and delivering tailored solutions.",
      link: undefined,
      githubLink: undefined,
      images: [],
      usedTechs: ["php", "html", "css", "javascript", "jquery", "sql", "mysql"],
      output: "Improved client communication and project management skills.",
    },
  },
] as TimelineEntryProps[];
