import type { TimelineItem } from "@/interfaces";

export default [
  {
    title: "Q4 2025",
    content: {
      id: 1,
      status: "ongoing",
      desc: "The playground is a full stack web project allowing develeopers to design with pre-defined motions which can be used in their React app components in one click.",
      techs: [
        "typescript",
        "react",
        "redux",
        "nextjs",
        "tailwindcss",
        "reactquery",
      ],
      title: "Motion Playgrounds",
      images: [
        "/assets/timeline/motion-playgrounds/1.webp",
        "/assets/timeline/motion-playgrounds/2.webp",
        "/assets/timeline/motion-docs/1.webp",
        "/assets/timeline/motion-docs/2.webp",
      ],
      gitLink: "https://github.com/Motion-Provider/motion-provider-playgrounds",
    },
  },
  {
    title: "Q3 2025",
    content: {
      id: 2,
      status: "done",
      desc: "Maintained E2E OCR app for Polish archaeologists. The project aims to interpret the handwritten surface of paper-works and transforming it collectively into a colorful projection/profile models by using computer vision.",
      images: [],
      techs: ["nodejs", "python", "javascript", "json", "yaml"],
      title: "Geo-OCR App",
    },
  },
  {
    title: "Q3 2025",
    content: {
      id: 3,
      status: "paused",
      title: "modulith.app",
      techs: [
        "react",
        "tailwindcss",
        "typescript",
        "nextjs",
        "supabase",
        "redux",
        "postgresql",
        "nodejs",
      ],
      desc: "A fullstack, real-time all-in-one portal that designed to create industry-specific digital CRMs with it's highly versatile & customizable module system. Enabling everyone to continue business or service without sticking the third parties.",
      images: [
        "/assets/timeline/modulith/modulith-2.webp",
        "/assets/timeline/modulith/modulith-1.webp",
        "/assets/timeline/modulith/modulith-3.webp",
        "/assets/timeline/modulith/modulith-4.webp",
      ],
    },
  },
  {
    title: "Q2 2025",
    content: {
      id: 4,
      images: [
        "/assets/timeline/beyazkose/gif-beyaz-kose.gif",
        "/assets/timeline/beyazkose/beyaz-kose-patiserrie-landing.png",
      ],
      status: "done",
      title: "beyazkose.com",
      techs: [
        "react",
        "tailwindcss",
        "typescript",
        "nextjs",
        "supabase",
        "redux",
      ],
      desc: "A one-day gig project aimed at developing restaurant QR menu app designed to showcase product listings to the end-customers.",
      gitLink: "https://github.com/Masculinn/qr-menu-restaurant-app",
    },
  },
  {
    title: "Q2 2025",
    content: {
      id: 5,
      status: "done",
      title: "izisarcheologia.com",
      techs: [
        "react",
        "tailwindcss",
        "typescript",
        "nextjs",
        "supabase",
        "redux",
      ],
      desc: "Full-stack archeology web app covering E2E enterprise development featuring: 25 years company portfolio, media presses, project areas as well as visual excavational fields with mapbox renderers.",
      gitLink: "https://github.com/Masculinn/izis",
      images: [
        "/assets/timeline/izis/1.webp",
        "/assets/timeline/izis/2.webp",
        "/assets/timeline/izis/3.webp",
        "/assets/timeline/izis/4.webp",
      ],
    },
  },
  {
    title: "Q2 2025",
    content: {
      id: 6,
      status: "done",
      title: "ovensandwich.com",
      techs: ["react", "tailwindcss", "typescript", "nextjs"],
      desc: "A carefully crafted SPA by valuing design and responsiveness. It contains various information about the restaurant, menu, and contact details.",
      gitLink: "https://github.com/Masculinn/ovensandwich",
      images: [
        "/assets/timeline/ovensandwich/1.webp",
        "/assets/timeline/ovensandwich/2.webp",
        "/assets/timeline/ovensandwich/3.webp",
        "/assets/timeline/ovensandwich/4.webp",
      ],
    },
  },
  {
    title: "Q1 2025",
    content: {
      id: 7,
      status: "done",
      title: "Motion Provider",
      gitLink: "https://github.com/Masculinn/motion-provider",
      techs: ["react", "tailwindcss", "typescript", "nextjs"],
      desc: "Accelerating the development of react component animations up to 4x with seamless performance and precision, built entirely with typescript for a smooth, type-safe development experience.",
      images: [
        "/assets/timeline/motion-provider-v1/saas-thumb.gif",
        "/assets/timeline/motion-provider-v1/crypto-thumb.gif",
        "/assets/timeline/motion-provider-v1/agency-thumb.gif",
        "/assets/timeline/motion-provider-v1/nft-thumb.gif",
      ],
    },
  },
  {
    title: "Q1 2025",
    content: {
      id: 8,
      status: "done",
      title: "burak.dev",
      desc: "First version of my portfolio app that you are currently visiting 😀",
      images: [],
      techs: [
        "react",
        "redux",
        "nextjs",
        "tailwindcss",
        "typescript",
        "shadcn",
        "supabase",
      ],
    },
  },
  {
    title: "Q4 2024",
    content: {
      id: 9,
      status: "paused",
      title: "teezy.com",
      desc: "Self-initiated social music platform where users can listen to music, create profiles, upload and share tracks, explore other profiles, and enjoy AI-modified versions of tracks. It aimed to be a more interactive and community-driven version of Spotify.",
      images: [
        "/assets/timeline/teezy/1.webp",
        "/assets/timeline/teezy/2.webp",
        "/assets/timeline/teezy/3.webp",
        "/assets/timeline/teezy/4.webp",
      ],
      techs: [
        "react",
        "redux",
        "tailwindcss",
        "typescript",
        "supabase",
        "nextjs",
        "postgresql",
      ],
    },
  },
  {
    title: "Q3 2024",
    content: {
      id: 10,
      status: "done",
      title: "ERP Cloudy",
      desc: "Promoted as a team lead for a high-stakes project integrating the Polish government invoice system (Krajowy System e-Faktur - KSEF) into company's ERP architecture. Collaborated with accountants, digitized processes, and managed team development.",
      images: [
        "/assets/timeline/erp-cloudy/1.webp",
        "/assets/timeline/erp-cloudy/2.webp",
      ],
      techs: ["javascript", "xml", "sap"],
    },
  },
  {
    title: "Q3 2024",
    content: {
      id: 11,
      status: "done",
      title: "Dashboard App",
      desc: "Developed and maintained all-in-one E2E foreign student platform, allowing Turkish students studying in Poland to track visa statuses, accommodations, appointments, and documents, with secure business logic as well as real-time communication channels.",
      images: [
        "/assets/timeline/olympos-dashboard/1.webp",
        "/assets/timeline/olympos-dashboard/2.webp",
        "/assets/timeline/olympos-dashboard/3.webp",
        "/assets/timeline/olympos-dashboard/4.webp",
      ],
      gitLink: "https://github.com/Masculinn/education-crm",
      techs: ["nextjs", "remix", "react", "redux", "supabase", "tailwindcss"],
    },
  },
  {
    title: "Q2 2024",
    content: {
      id: 12,
      status: "done",
      title: "atlanticmedi.com",
      desc: "Built a static medical tourism web app consisting over 165 pages with internationalization(EN/PL). Scraped comprehensive informations from partner's knowledge-house containing medical treatments and services and combined all into a single monorepo with real-time chat-bot support.",
      images: [
        "/assets/timeline/atlanticmedi/1.webp",
        "/assets/timeline/atlanticmedi/2.webp",
        "/assets/timeline/atlanticmedi/3.webp",
        "/assets/timeline/atlanticmedi/4.webp",
      ],
      techs: ["nextjs", "react", "redux", "threejs", "tailwindcss"],
    },
  },
  {
    title: "Q1 2024",
    content: {
      id: 13,
      status: "done",
      title: "olymposedu.com",
      desc: "Developed a company portfolio web app where students can learn about their educational opportunities by aspiring them to study in Poland, including information on universities, pricing, articles, and more.",
      images: [
        "/assets/timeline/olymposedu/1.webp",
        "/assets/timeline/olymposedu/2.webp",
        "/assets/timeline/olymposedu/3.webp",
        "/assets/timeline/olymposedu/4.webp",
      ],
      gitLink: "https://github.com/Masculinn/olymposedu",
      techs: ["nextjs", "remix", "react", "redux", "supabase"],
    },
  },
  {
    title: "Q4 2023",
    content: {
      id: 14,
      status: "done",
      title: "finfluencer.com",
      desc: "Developed a SPA integrated into the company's website for business analytics for Turkish financial influencers.",
      images: [
        "/assets/timeline/finfluencer/1.webp",
        "/assets/timeline/finfluencer/2.webp",
        "/assets/timeline/finfluencer/3.webp",
        "/assets/timeline/finfluencer/4.webp",
      ],
      gitLink: "https://github.com/Masculinn/olymposedu",
      techs: ["nextjs", "react", "redux"],
    },
  },
  {
    title: "Q4 2023",
    content: {
      id: 15,
      status: "done",
      title: "santaesmeraldas.com",
      desc: "Developed a cross-platform for Etsy one of the top seller jewelry e-commerce brand from scratch, listing over 150+ highly-valued products that made over $1M. Focused on improving UX, SEO optimization by caring LCP, CLS, TTFB, A/B testing. Mainly focused on converting the business model to feasible online sales.",
      images: [
        "/assets/timeline/santa-esmeralda/1.webp",
        "/assets/timeline/santa-esmeralda/2.webp",
        "/assets/timeline/santa-esmeralda/3.webp",
        "/assets/timeline/santa-esmeralda/4.webp",
      ],
      techs: ["shopify", "javascript", "css", "html"],
    },
  },
  {
    title: "Q3 2023",
    content: {
      id: 16,
      images: [],
      status: "done",
      title: "ERP Cloudy",
      techs: ["javascript", "xml", "sap"],
      desc: "Joined the largest e-transformation software firm based on Turkey, serving over 370K+ clients. Simultaneously worked at a consulting firm. Focused on understanding and implementing solutions for the government e-invoice system (Krajowy System e-Faktur - KSEF). Primarily worked as an integrator developer by focusing system-based solutions and supporting the team.",
    },
  },
  {
    title: "Q2 2023",
    content: {
      id: 17,
      images: [
        "/assets/timeline/atlantic/1.webp",
        "/assets/timeline/atlantic/2.webp",
      ],
      status: "done",
      title: "atlanticvalleypartners.com",
      techs: ["nextjs", "react", "redux", "tailwindcss"],
      desc: "Developed the company's portfolio with internationalization(EN/PL/TR) website with a focus on optimization, accessibility, and user experience. Collaborated with the design team to ensure the website met accessibility standards and provided a smooth user experience.",
      gitLink: "https://github.com/Masculinn/atlanticvalleypartners",
    },
  },
  {
    title: "2022",
    content: {
      id: 18,
      status: "done",
      title: "The Last Human",
      desc: "Finished my internship at Insider where I worked on a mobile non-stop survival game using the Unity game engine.",
      images: [],
      techs: ["unity"],
    },
  },
  {
    title: "2021",
    content: {
      id: 19,
      status: "done",
      title: "Freelancer",
      desc: "Worked on various freelancing platforms like Fiverr and Upwork, creating web applications based on client requirements. Gained experience in understanding client needs and delivering tailored solutions.",
      images: [],
      techs: ["php", "html", "css", "javascript", "jquery", "mysql"],
    },
  },
] as const satisfies TimelineItem[];
